spring:
  application:
    name: core-banking-psdx
    version: 1.0.0
    description: PSD2/PSD3 and FIDA Regulatory Compliance Service
    team:
      name: Catalis Development
      email: dev@catalis.com

  r2dbc:
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=${DB_SSL_MODE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=${DB_SSL_MODE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  threads:
    virtual:
      enabled: true

server:
  port: 8080
  shutdown: graceful

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
    docExpansion: none
    filter: true
  packages-to-scan: com.firefly.core.banking.psdx.web.controllers
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Integration with other microservices
integration:
  customer-mgmt:
    enabled: ${CUSTOMER_MGMT_ENABLED:false}
    base-url: "${CUSTOMER_MGMT_URL:http://common-platform-customer-mgmt:8080}"
    timeout: 5000
  contract-mgmt:
    enabled: ${CONTRACT_MGMT_ENABLED:false}
    base-url: "${CONTRACT_MGMT_URL:http://common-platform-contract-mgmt:8080}"
    timeout: 5000
  accounts:
    enabled: ${ACCOUNTS_ENABLED:false}
    base-url: "${ACCOUNTS_URL:http://core-banking-accounts:8080}"
    timeout: 5000
  cards:
    enabled: ${CARDS_ENABLED:false}
    base-url: "${CARDS_URL:http://core-banking-cards:8080}"
    timeout: 5000
  payment-hub:
    enabled: ${PAYMENT_HUB_ENABLED:false}
    base-url: "${PAYMENT_HUB_URL:http://core-banking-payment-hub:8080}"
    timeout: 5000
  ledger:
    enabled: ${LEDGER_ENABLED:false}
    base-url: "${LEDGER_URL:http://core-banking-ledger:8080}"
    timeout: 5000
  sca-mgmt:
    enabled: ${SCA_MGMT_ENABLED:false}
    base-url: "${SCA_MGMT_URL:http://common-platform-sca-mgmt:8080}"
    timeout: 5000

# PSD2/PSD3 and FIDA Configuration
psdx:
  api:
    base-url: ${API_BASE_URL:http://localhost:8080}
  consent:
    default-expiry-days: 90
  security:
    token-validity-seconds: 3600
    refresh-token-validity-days: 30
    jwt:
      secret: ${JWT_SECRET:ChangeThisToASecureSecretKeyInProduction}
    encryption:
      enabled: true
      algorithm: AES/GCM/NoPadding
      secret-key: ${ENCRYPTION_SECRET:ChangeThisToASecureSecretKeyInProduction}
  tpp:
    validation:
      enabled: true
      certificate-validation: true
  logging:
    retention-days: 365
  sca:
    required-for-all-payments: true
    exemption-threshold-amount: 30.00
    exemption-threshold-currency: EUR

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.firefly: DEBUG
    org.springframework.r2dbc: DEBUG
    org.flywaydb: DEBUG

---
spring:
  config:
    activate:
      on-profile: testing

logging:
  level:
    root: INFO
    com.firefly: DEBUG
    org.springframework.r2dbc: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.firefly: INFO
    org.springframework: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false